<?php

/**
 * @file
 * API Access module definitions.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function api_access_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'system_site_information_settings') {

    $api_key = \Drupal::config('system.site')->get('siteapikey');
    $value = $api_key ? $api_key : t('No API Key yet');
    $form['site_information']['siteapikey'] = [
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#default_value' => $value,
      '#required' => TRUE,
      '#description' => t('Add your API Key here.'),
    ];
    $form['actions']['submit']['#value'] = t('Update Configuration');

    $form['#submit'][] = 'api_access_site_information_settings_submit';
  }
}

/**
 * Custom submit handler.
 */
function api_access_site_information_settings_submit(&$form, FormStateInterface $form_state) {
  $api_key = $form_state->getValue('siteapikey');
  $config = \Drupal::service('config.factory')->getEditable('system.site');
  $config
    ->set('siteapikey', $api_key)
    ->save();
  \Drupal::messenger()->addStatus(t('The site API Key has been saved <em>@api_key</em>', ['@api_key' => $api_key]));
}
